
name: Library Retake Exam CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code.
        uses: actions/checkout@v3
      - name: Use Node.js '18.x'.
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Build our WebApp and install dependencies.
        run: npm install
      - name: Run Unit tests to check our WebApp.
        run: npm run test:unit
      - name: Display my SoftUni username.
        run: echo "qceka88"
      
